### ISSUE TITLE
data migration > EAV Step error

### ISSUE THREAD

**Issue by Vincenkt** [magento/data-migration-tool-ce#10]
Anyone having this issue?
( data migration > EAV Step)
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-Migration_Default' for key 'EAV_ATTRIBUTE_SET_ENTITY_TYPE_ID_ATTRIBUTE_SET_NAME'

**Comment by jgmage** [comment]
I ran into this.  If this is the error I recall, it was some source_models that didn't exist in my destination db.  I ran the following for each of the troublesome ones as I recall.
   update eav_attribute set source_model=NULL where source_model='mana_filters/source_filterable';
   update eav_attribute set source_model=NULL where source_model='mana_filters/source_display';
   ... etc...

**Comment by surfer190** [comment]
Run this on the magento 2 site (That has migrated data already presumably):

`DELETE FROM eav_attribute_set WHERE attribute_set_name != 'Default';`

**Comment by dfelton** [comment]
@surfer190 This is **not** a good recommendation.

**Comment by schizek** [comment]
I know this is already closed, but just for clarification in case anyone else has this same issue.  This particular one appears caused by an old extension that has since been removed which I believe was Mana_Filters https://www.manadev.com/advanced-layered-navigation-ce

The leftover data in the DB will need to be manually removed to clean it out of the system.
