### ISSUE TITLE
Custom module transferring data

### ISSUE THREAD

**Issue by craigcarnell** [magento/data-migration-tool-ce#32]
How do I get the tool to simply copy the data from custom modules (such as tables) to the new M2 database?

If I recreate the module that is fine, but then I get an error such as:

```
[2015-12-14 14:07:25][ERROR]: Destination documents are missing or not mapped: mst_core_urlrewrite,mst_misspell_index,mst_misspell_suggest,mst_search_index,mst_search_stopword,mst_search_synonym
```

How do I go about transferring this? I have installed the M2 version of the module

**Comment by ilol** [comment]
@craigcarnell You should describe you custom data structure in config file.

**Comment by craigcarnell** [comment]
@ilol I appreciate that, but how? :)

**Comment by craigcarnell** [comment]
@ilol The documentation tells you how to ignore something, but not to simply copy the data across as the 2 modules exist in M1 and M2

**Comment by quangdog** [comment]
How about just manually copying the tables using sql statements yourself?  Then telling the migrator to ignore the tables in the source database....

**Comment by craigcarnell** [comment]
@quangdog That kind of defeats the purpose of the data migration tool if it doesn't have that ability. Also you would also need to do this when doing an update.

**Comment by quangdog** [comment]
I believe that the migrator's approach is that if a table exists in M1 and M2, and the structure is the same, then the records from M1 will just copy straight to M2 *without* needing to specify any mapping.

So, rather than copy the entire table + data from M1 to M2 manually, just create the structure for the table in M2, and *don't* specifically map the table at all in the migrator.  The data should move with the migration, and should be kept up to date with incrementals.

But what the heck do I know - I'm still trying to get my M1 to migrate to M2 without losing random bits of customer data along the way. ;-(

**Comment by victor-v-rad** [comment]
>I believe that the migrator's approach is that if a table exists in M1 and M2, and the structure is the same, then the records from M1 will just copy straight to M2 without needing to specify any mapping.

Absolutely right

**Comment by ilol** [comment]
@craigcarnell if you got an answer, please close the issue. Thanks
